from finta import TA


df.columns = ['date', 'close', 'volume']
df.set_index('date', inplace=True)

ohlc = df["close"].ohlc()
df['AO'] = TA.AO(ohlc)
df['EMA'] = TA.EMA(ohlc)
df['DEMA'] = TA.DEMA(ohlc)
df['TEMA'] = TA.TEMA(ohlc)
df['TRIX'] = TA.TRIX(ohlc)
df['TRIMA'] = TA.TRIMA(ohlc)
df['VAMA'] = TA.VAMA(ohlc)
df['ER'] = TA.ER(ohlc)
df['KAMA'] = TA.KAMA(ohlc)
df['ZLEMA'] = TA.ZLEMA(ohlc)
df['HMA'] = TA.HMA(ohlc)
df['EVWMA'] = TA.EVWMA(ohlc)
df['MACD'] = TA.MACD(ohlc)
df['TR'] = TA.TR(ohlc)
df['ATR'] = TA.ATR(ohlc)
df['SAR'] = TA.SAR(ohlc)
df['PIVOT_FIB'] = TA.PIVOT_FIB(ohlc)
df['UO'] = TA.UO(ohlc)
df['MI'] = TA.MI(ohlc)
df['VORTEX'] = TA.VORTEX(ohlc)
df['TSI'] = TA.TSI(ohlc)
df['CHAIKIN'] = TA.CHAIKIN(ohlc)
df['MFI'] = TA.MFI(ohlc)
df['VZO'] = TA.VZO(ohlc)
df['PZO'] = TA.PZO(ohlc)
df['EFI'] = TA.EFI(ohlc)
df['CFI'] = TA.CFI(ohlc)
df['EBBP'] = TA.EBBP(ohlc)
df['CMO'] = TA.CMO(ohlc)
df['CHANDELIER'] = TA.CHANDELIER(ohlc)
df['QSTICK'] = TA.QSTICK(ohlc)
df['TMF'] = TA.TMF(ohlc)
df['WTO'] = TA.WTO(ohlc)
df['FISH'] = TA.FISH(ohlc)
df['ICHIMOKU'] = TA.ICHIMOKU(ohlc)
df['VR'] = TA.VR(ohlc)
df['SQZMI'] = TA.SQZMI(ohlc)
df['VPT'] = TA.VPT(ohlc)
df['VFI'] = TA.VFI(ohlc)
df['MSD'] = TA.MSD(ohlc)
print (df)
